require('dotenv').config()
const mongoose = require('mongoose')
const connectDB = require('./config/db')
const Room = require('./models/Room')

async function seed() {
  try {
    await connectDB()

    // Clear existing rooms
    await Room.deleteMany({})

    const rooms = [
      {
        name: 'Standard Apartment',
        slug: 'standard-apartment',
        description: 'Zgjidhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/images/standard-apartment.jpg',
        amenities: ['1 dhomë gjumi', 'Wi-Fi', 'Kuzhinë e vogël', 'Banjo private'],
      },
      {
        name: 'City Apartment 16',
        slug: 'city-apartment-16',
        description: 'Qëndrim premium në lokacion qendror me komoditet të plotë.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/apartment16.jpeg',
        gallery: ['/apartment16.jpeg','/foto7.avif','/foto8.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 17',
        slug: 'city-apartment-17',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment17.jpeg',
        gallery: ['/apartment17.jpeg','/foto9.avif','/foto10.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 18',
        slug: 'city-apartment-18',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment2.jpeg',
        gallery: ['/apartment2.jpeg','/foto11.avif','/foto99.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 19',
        slug: 'city-apartment-19',
        description: 'Qëndrim premium në lokacion qendror me komoditet të plotë.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/apartment19.jpeg',
        gallery: ['/apartment19.jpeg','/foto1.avif','/foto2.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 20',
        slug: 'city-apartment-20',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment11.jpeg',
        gallery: ['/apartment11.jpeg','/foto4.avif','/foto6.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 21',
        slug: 'city-apartment-21',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment14.jpeg',
        gallery: ['/apartment14.jpeg','/foto7.avif','/foto8.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 22',
        slug: 'city-apartment-22',
        description: 'Qëndrim premium në lokacion qendror me komoditet të plotë.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/apartment18.jpeg',
        gallery: ['/apartment18.jpeg','/foto9.avif','/foto10.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 23',
        slug: 'city-apartment-23',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment20.jpeg',
        gallery: ['/apartment20.jpeg','/foto11.avif','/foto99.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 24',
        slug: 'city-apartment-24',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment21.jpeg',
        gallery: ['/apartment21.jpeg','/foto1.avif','/foto2.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 25',
        slug: 'city-apartment-25',
        description: 'Qëndrim premium në lokacion qendror me komoditet të plotë.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/apartment22.jpeg',
        gallery: ['/apartment22.jpeg','/foto4.avif','/foto6.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 26',
        slug: 'city-apartment-26',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment23.jpeg',
        gallery: ['/apartment23.jpeg','/foto7.avif','/foto8.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 27',
        slug: 'city-apartment-27',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment24.jpeg',
        gallery: ['/apartment24.jpeg','/foto9.avif','/foto10.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 28',
        slug: 'city-apartment-28',
        description: 'Qëndrim premium në lokacion qendror me komoditet të plotë.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/apartment25.jpeg',
        gallery: ['/apartment25.jpeg','/foto11.avif','/foto99.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 29',
        slug: 'city-apartment-29',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment26.jpeg',
        gallery: ['/apartment26.jpeg','/foto1.avif','/foto2.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 30',
        slug: 'city-apartment-30',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment27.jpeg',
        gallery: ['/apartment27.jpeg','/foto4.avif','/foto6.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      }
      ,
      {
        name: 'City Apartment 09',
        slug: 'city-apartment-09',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment9.jpeg',
        gallery: ['/apartment9.jpeg','/foto1.avif','/foto2.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 10',
        slug: 'city-apartment-10',
        description: 'Qëndrim premium në lokacion qendror me komoditet të plotë.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/apartment10.jpeg',
        gallery: ['/apartment10.jpeg','/foto4.avif','/foto6.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 11',
        slug: 'city-apartment-11',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment1.jpeg',
        gallery: ['/apartment1.jpeg','/foto7.avif','/foto8.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 12',
        slug: 'city-apartment-12',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment12.jpeg',
        gallery: ['/apartment12.jpeg','/foto9.avif','/foto10.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 13',
        slug: 'city-apartment-13',
        description: 'Qëndrim premium në lokacion qendror me komoditet të plotë.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/apartment13.jpeg',
        gallery: ['/apartment13.jpeg','/foto11.avif','/foto99.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 14',
        slug: 'city-apartment-14',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment3.jpeg',
        gallery: ['/apartment3.jpeg','/foto1.avif','/foto2.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 15',
        slug: 'city-apartment-15',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment15.jpeg',
        gallery: ['/apartment15.jpeg','/foto4.avif','/foto6.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      // Additional apartments for full inventory (City Apartment 04..30)
      {
        name: 'City Apartment 04',
        slug: 'city-apartment-04',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment4.jpeg',
        gallery: ['/apartment4.jpeg','/foto1.avif','/foto2.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 05',
        slug: 'city-apartment-05',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment5.jpeg',
        gallery: ['/apartment5.jpeg','/foto4.avif','/foto6.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 06',
        slug: 'city-apartment-06',
        description: 'Apartament modern me ambient të ndriçuar dhe hapësirë të rehatshme.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/apartment6.jpeg',
        gallery: ['/apartment6.jpeg','/foto7.avif','/foto8.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 07',
        slug: 'city-apartment-07',
        description: 'Qëndrim premium në lokacion qendror me komoditet të plotë.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/apartment7.jpeg',
        gallery: ['/apartment7.jpeg','/foto9.avif','/foto10.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'City Apartment 08',
        slug: 'city-apartment-08',
        description: 'Zgjedhje praktike dhe komode për qëndrime të shkurtra në qytet.',
        basePricePerNight: 120,
        maxGuests: 2,
        imageUrl: '/apartment8.jpeg',
        gallery: ['/apartment8.jpeg','/foto11.avif','/foto99.avif'],
        amenities: ['Wi-Fi','Kuzhinë','Banjo private','TV'],
      },
      {
        name: 'Deluxe Apartment',
        slug: 'deluxe-apartment',
        description: 'Apartament më i gjerë me dizajn modern dhe më shumë rehati.',
        basePricePerNight: 150,
        maxGuests: 2,
        imageUrl: '/images/deluxe-apartment.jpg',
        amenities: ['1-2 dhoma', 'Ambient i ndriçuar', 'Kuzhinë', 'TV'],
      },
      {
        name: 'Premium City Stay',
        slug: 'premium-city-stay',
        description: 'Qëndrim premium në lokacion qendror për eksperiencë më të kompletuar.',
        basePricePerNight: 190,
        maxGuests: 2,
        imageUrl: '/images/premium-city-stay.jpg',
        amenities: ['Pamje qyteti', 'Hapësirë më e madhe', 'Stil modern', 'Pajisje të plota'],
      },
    ]

    const inserted = await Room.insertMany(rooms)
    console.log(`Inserted ${inserted.length} rooms`) // expected 3

    process.exit(0)
  } catch (err) {
    console.error('Seed error:', err)
    process.exit(1)
  }
}

seed()
